# Generated by Django 5.2 on 2025-04-20 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_autor_nombre_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
