# Generated by Django 5.2 on 2025-04-20 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
